from sqlmodel import create_engine, SQLModel, Session

DATABASE_URL = "sqlite:///./shortener.db"
engine = create_engine(DATABASE_URL, echo=True)
#NOTE: echo=True is used for debugging purposes, it will log all the SQL statements generated by SQLModel. Set it to False in production.
def get_session():
    """
    Create a new DB session for each request.
    Use with FastAPI dependency injection.
    """
    with Session(engine) as session:
        yield session
        
def init_db():
    from models.models import URL  
    SQLModel.metadata.create_all(engine)